### ISSUE TITLE
postgresql 연동

### ISSUE THREAD

**Issue by Lurang** [AdsRider/abc#5]
데이터 저장을 위해 postgresql 연동이 필요함

postgresql과 연동하는 부분을 pgpool, sloink 등등 어떤 library를 이용할것인지 정하고

schema정의가 필요함

schema의경우 backend api에서도 필요할텐데 repo 를 분리할거면 관리를 어떻게 할건지 고민이 필요함

**Comment by Lurang** [comment]
#6  에서 진행중

**Comment by oni-nick** [comment]
#4 연결 테스트

**Comment by Lurang** [comment]
slonik 을 이용해 pool 을 넘겨받는 방식으로 진행하였고

backend api도 그냥 같은 레포에서 관리하는 방식으로 진행하였음

schema의 경우 필요한항목이 생길때마다 추가할예정
